### ISSUE TITLE
Feature to select number of stars when creating a galaxy

### ISSUE THREAD

**Issue by Ojansen** [HoneyTauOverTwo/DSPSeedSearch#2]
When you create a new galaxy the number of stars is always set to 64, can it be possible to search all of the 64 galaxies?

**Comment by HoneyTauOverTwo** [comment]
Sorry I don't think I understand your question.

**Comment by Ojansen** [comment]
In some galaxies there are more blue giants when there are just 45 for example, so searching through all of the posibilities eg 32 - 64 there might be a better seed in those

**Comment by Ojansen** [comment]
In seed 93246841 the 64 stars has 3 giant stars but no blue giant while the 50 stars one has 2 blue giants.

**Comment by HoneyTauOverTwo** [comment]
Oh I see, I'm pretty sure I can just add this as another setting in the text file, I vaguely remember that I used the default settings to search the seeds, but there is a way to change the number of stars.

I will close this issue for now, as it is a feature request. I will let you know when I get around to implementing it.
