### ISSUE TITLE
Feature to scan every planet in one galaxy

### ISSUE THREAD

**Issue by Ojansen** [HoneyTauOverTwo/DSPSeedSearch#4]
seeing all the resources and dysonLuminosity from every star and distance from the home planet. And seeing how many planets the home planet has and other planets or just the brightest stars.

**Comment by HoneyTauOverTwo** [comment]
Pretty sure it is not difficult to access this info. Got to have a think for how to output it.

**Comment by Ojansen** [comment]
it might be an idea to plot is on a 2d scatter chart and save it as an image, or even better and 3d scatter chart with a legend like the one when you create an new game

**Comment by HoneyTauOverTwo** [comment]
Well, the idea of how to output it is great, but sounds like a lot of work. This started as a simple tool just to search one specific thing: Seeds with the biggest star.

Getting it to search through planets should not be hard by modifying the code thou. I *might* do it in the future.

If someone decides to implement it and set a pull request I would gladly review the code and test it.
